### ISSUE TITLE
Possibility of dual licensing to MIT License

### ISSUE THREAD

**Issue by robinsonkwame** [Lambda-3/DiscourseSimplification#11]
Would it possible to dual license this work as MIT license? Businesses may want to use this work and contribute back improvements but are unwilling to GPL their commercial offerings.

**Comment by bermeitinger-b** [comment]
Paging @Mischn and @cniklaus , do we have a reason why GPL was chosen in the first place? Stargraph and Indra are both MIT as well. If we change it here, also Graphene should be changed.

**Comment by robinsonkwame** [comment]
Any follow up on this? I would love to use DiscourseSimplification to power an NLP background and contribute back any improvements or bug fixes along the way.

**Comment by bermeitinger-b** [comment]
We discussed this and didn't find any reasons not to change. Please wait a few days for us to change it everywhere.

**Comment by bermeitinger-b** [comment]
I'm sorry for the delay.

The license was chosen deliberately because we rely on CoreNLP [(license)](https://stanfordnlp.github.io/CoreNLP/#license) and must be GPL as well. We're thinking of a way to "circumvent" this but it will not be possible to do this within the coming days or weeks.
